[package]
name = "psw-gen"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = [ "k3nder" ]
description = "A simple passworld generator"


[dependencies]
rand = "0.9.0-alpha.2"
clap = { version = "4.5.20", features = ["derive"] }